server {
    listen 8080;
    server_name _;
    root /var/www/html/public;
    index index.php index.html;

    charset utf-8;
    client_max_body_size 100M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /storage/ {
        alias /var/www/html/storage/app/public/;
        access_log off;
        expires 30d;
        add_header Cache-Control "public";
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_pass laravel-app:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
        fastcgi_buffer_size 256k;
        fastcgi_buffers 32 256k;
        fastcgi_busy_buffers_size 512k;
        fastcgi_read_timeout 360s;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
